import 'country_address.dart';

final countryAddresses = {
  'pl': CountryAddress(
    'pl',
    displayFormat: {
      'pl': [
        [DisplayAddressPart.firstName, ' ', DisplayAddressPart.lastName],
        [DisplayAddressPart.company],
        [DisplayAddressPart.address1],
        [DisplayAddressPart.address2],
        [DisplayAddressPart.postalCode, ' ', DisplayAddressPart.city],
        [DisplayAddressPart.phone],
      ],
    },
    formFormat: [
      [FormAddressPart.firstName.field(), FormAddressPart.lastName.field()],
      [FormAddressPart.company.field()],
      [FormAddressPart.address1.field()],
      [FormAddressPart.address2.field()],
      [FormAddressPart.postalCode.field(), FormAddressPart.city.field(2)],
      [FormAddressPart.phone.field()],
    ],
  ),
  'us': CountryAddress(
    'us',
    displayFormat: {
      'en': [
        [DisplayAddressPart.firstName, ' ', DisplayAddressPart.lastName],
        [DisplayAddressPart.company],
        [DisplayAddressPart.address1],
        [DisplayAddressPart.address2],
        [
          DisplayAddressPart.city,
          ', ',
          DisplayAddressPart.zone,
          ' ',
          DisplayAddressPart.postalCode
        ],
        [DisplayAddressPart.phone],
      ],
    },
    formFormat: [],
    zoneNames: {
      'AL': {'en': 'Alabama'},
      'AK': {'en': 'Alaska'},
      'AZ': {'en': 'Arizona'},
      'AR': {'en': 'Arkansas'},
      'CA': {'en': 'California'},
      'CO': {'en': 'Colorado'},
      'CT': {'en': 'Connecticut'},
      'DE': {'en': 'Delaware'},
      'FL': {'en': 'Florida'},
      'GA': {'en': 'Georgia'},
      'HI': {'en': 'Hawaii'},
      'ID': {'en': 'Idaho'},
      'IL': {'en': 'Illinois'},
      'IN': {'en': 'Indiana'},
      'IA': {'en': 'Iowa'},
      'KS': {'en': 'Kansas'},
      'KY': {'en': 'Kentucky'},
      'LA': {'en': 'Louisiana'},
      'ME': {'en': 'Maine'},
      'MD': {'en': 'Maryland'},
      'MA': {'en': 'Massachusetts'},
      'MI': {'en': 'Michigan'},
      'MN': {'en': 'Minnesota'},
      'MS': {'en': 'Mississippi'},
      'MO': {'en': 'Missouri'},
      'MT': {'en': 'Montana'},
      'NE': {'en': 'Nebraska'},
      'NV': {'en': 'Nevada'},
      'NH': {'en': 'New Hampshire'},
      'NJ': {'en': 'New Jersey'},
      'NM': {'en': 'New Mexico'},
      'NY': {'en': 'New York'},
      'NC': {'en': 'North Carolina'},
      'ND': {'en': 'North Dakota'},
      'OH': {'en': 'Ohio'},
      'OK': {'en': 'Oklahoma'},
      'OR': {'en': 'Oregon'},
      'PA': {'en': 'Pennsylvania'},
      'RI': {'en': 'Rhode Island'},
      'SC': {'en': 'South Carolina'},
      'SD': {'en': 'South Dakota'},
      'TN': {'en': 'Tennessee'},
      'TX': {'en': 'Texas'},
      'UT': {'en': 'Utah'},
      'VT': {'en': 'Vermont'},
      'VA': {'en': 'Virginia'},
      'WA': {'en': 'Washington'},
      'WV': {'en': 'West Virginia'},
      'WI': {'en': 'Wisconsin'},
      'WY': {'en': 'Wyoming'},
      'DC': {'en': 'District of Columbia'},
    },
  ),
  'ca': CountryAddress(
    'ca',
    displayFormat: {
      'en': [
        [DisplayAddressPart.firstName, ' ', DisplayAddressPart.lastName],
        [DisplayAddressPart.company],
        [DisplayAddressPart.address1],
        [DisplayAddressPart.address2],
        [
          DisplayAddressPart.city,
          ' ',
          DisplayAddressPart.zone,
          '  ',
          DisplayAddressPart.postalCode,
        ],
        [DisplayAddressPart.phone],
      ],
      'fr': [
        [DisplayAddressPart.firstName, ' ', DisplayAddressPart.lastName],
        [DisplayAddressPart.company],
        [DisplayAddressPart.address1],
        [DisplayAddressPart.address2],
        [
          DisplayAddressPart.city,
          ' (',
          DisplayAddressPart.fullZone,
          ')  ',
          DisplayAddressPart.postalCode,
        ],
        [DisplayAddressPart.phone],
      ],
    },
    formFormat: [],
    zoneNames: {
      'AB': {
        'en': 'Alberta',
        'fr': 'Alberta',
      },
      'BC': {
        'en': 'British Columbia',
        'fr': 'Colombie-Britannique',
      },
      'MB': {
        'en': 'Manitoba',
        'fr': 'Manitoba',
      },
      'NB': {
        'en': 'New Brunswick',
        'fr': 'Nouveau-Brunswick',
      },
      'NL': {
        'en': 'Newfoundland and Labrador',
        'fr': 'Terre-Neuve-et-Labrador',
      },
      'NS': {
        'en': 'Nova Scotia',
        'fr': 'Nouvelle-Écosse',
      },
      'ON': {
        'en': 'Ontario',
        'fr': 'Ontario',
      },
      'PE': {
        'en': 'Prince Edward Island',
        'fr': 'Île-du-Prince-Édouard',
      },
      'QC': {
        'en': 'Quebec',
        'fr': 'Québec',
      },
      'SK': {
        'en': 'Saskatchewan',
        'fr': 'Saskatchewan',
      },
      'NT': {
        'en': 'Northwest Territories',
        'fr': 'Territoires du Nord-Ouest',
      },
      'NU': {
        'en': 'Nunavut',
        'fr': 'Nunavut',
      },
      'YT': {
        'en': 'Yukon',
        'fr': 'Yukon',
      },
    },
  ),
};
